version: '3.8'

services:
  frontend:
    image: ghcr.io/rinalis/film-react-nest:sha-f00636b55ac15a75159906f3b2b351695476cfcb-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ghcr.io/rinalis/film-react-nest:sha-f00636b55ac15a75159906f3b2b351695476cfcb
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=films
      - DATABASE_LOGGING=true
      - LOGGER_TYPE=json
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=films
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 